# Generated by Django 3.0.8 on 2020-07-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bank',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='branchdetails',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='branchdetails',
            name='bank',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='bank.Bank'),
        ),
        migrations.AlterField(
            model_name='branchdetails',
            name='branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='branchdetails',
            name='district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='branchdetails',
            name='ifsc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
